# Generated by Django 4.0 on 2021-12-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='Alex', max_length=20),
            preserve_default=False,
        ),
    ]
