# Generated by Django 4.0 on 2021-12-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_application', '0002_person_alter_todo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('urgent', 'urgent'), ('not urgent', 'not urgent')], default='not urgent', max_length=200),
        ),
    ]
