# Generated by Django 4.0 on 2021-12-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
