# Generated by Django 4.0 on 2021-12-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_person_todo_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
